# Comprehensive Car Database
CAR_MAKES_MODELS = {
    "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5", "S6", "S7", "S8"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "i8", "iX", "M2", "M3", "M4", "M5", "M8"],
    "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "S-Class", "V-Class", "AMG GT", "EQA", "EQB", "EQC", "EQE", "EQS"],
    "Toyota": ["Corolla", "Camry", "RAV4", "Highlander", "4Runner", "Tacoma", "Tundra", "Land Cruiser", "Prius", "Avalon", "Sienna", "Supra", "86", "C-HR", "Venza", "Yaris", "Mirai"],
    "Honda": ["Civic", "Accord", "CR-V", "HR-V", "Pilot", "Odyssey", "Ridgeline", "Passport", "Fit", "Insight", "Clarity", "NSX", "Jazz"],
    "Ford": ["Fiesta", "Focus", "Fusion", "Mustang", "Explorer", "Escape", "Edge", "Expedition", "F-150", "Ranger", "Bronco", "Maverick", "Transit", "EcoSport", "Mustang Mach-E"],
    "Chevrolet": ["Spark", "Sonic", "Cruze", "Malibu", "Camaro", "Corvette", "Trax", "Equinox", "Blazer", "Traverse", "Tahoe", "Suburban", "Silverado", "Colorado", "Bolt"],
    "Volkswagen": ["Polo", "Golf", "Jetta", "Passat", "Arteon", "Tiguan", "Atlas", "Touareg", "T-Roc", "T-Cross", "ID.3", "ID.4", "ID.Buzz"],
    "Nissan": ["Versa", "Sentra", "Altima", "Maxima", "370Z", "GT-R", "Kicks", "Rogue", "Murano", "Pathfinder", "Armada", "Frontier", "Titan", "Leaf"],
    "Hyundai": ["Accent", "Elantra", "Sonata", "Azera", "Veloster", "Kona", "Tucson", "Santa Fe", "Palisade", "Venue", "Ioniq", "Ioniq 5", "Ioniq 6"],
    "Kia": ["Rio", "Forte", "K5", "Stinger", "Soul", "Seltos", "Sportage", "Sorento", "Telluride", "Carnival", "Niro", "EV6"],
    "Mazda": ["Mazda2", "Mazda3", "Mazda6", "MX-5 Miata", "CX-3", "CX-30", "CX-5", "CX-50", "CX-9", "CX-90"],
    "Subaru": ["Impreza", "Legacy", "Outback", "Forester", "Crosstrek", "Ascent", "BRZ", "WRX", "Solterra"],
    "Lexus": ["IS", "ES", "GS", "LS", "RC", "LC", "UX", "NX", "RX", "GX", "LX", "RZ"],
    "Porsche": ["718", "911", "Panamera", "Cayenne", "Macan", "Taycan"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
    "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40"],
    "Jaguar": ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
    "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar"],
    "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Wagoneer", "Grand Wagoneer"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey"],
    "Ram": ["1500", "2500", "3500", "ProMaster"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Acura": ["ILX", "TLX", "RLX", "NSX", "RDX", "MDX"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
    "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
    "Mini": ["Cooper", "Countryman", "Clubman", "Convertible"],
    "Fiat": ["500", "500X", "500L", "Tipo", "Panda"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
    "Maserati": ["Ghibli", "Quattroporte", "Levante", "GranTurismo", "MC20"],
    "Ferrari": ["Roma", "Portofino", "F8", "SF90", "812", "296"],
    "Lamborghini": ["Huracan", "Aventador", "Urus"],
    "Bentley": ["Continental GT", "Flying Spur", "Bentayga"],
    "Rolls-Royce": ["Ghost", "Wraith", "Dawn", "Phantom", "Cullinan"],
    "Aston Martin": ["DB11", "DBS", "Vantage", "DBX"],
    "McLaren": ["GT", "Artura", "720S", "765LT"],
    "Bugatti": ["Chiron", "Divo"],
    "Peugeot": ["208", "308", "508", "2008", "3008", "5008"],
    "Renault": ["Clio", "Megane", "Captur", "Kadjar", "Koleos", "Talisman"],
    "Citroën": ["C3", "C4", "C5", "Berlingo"],
    "Skoda": ["Fabia", "Octavia", "Superb", "Kodiaq", "Karoq", "Kamiq"],
    "Seat": ["Ibiza", "Leon", "Ateca", "Tarraco", "Arona"],
    "Mitsubishi": ["Mirage", "Outlander", "Eclipse Cross", "Pajero"],
    "Suzuki": ["Swift", "Vitara", "S-Cross", "Jimny"],
}

CAR_MODELS_UPDATE = {
    "Arcfox": [
        "Arcfox αT",
        "Arcfox αS",
        "Arcfox αS5",
        "Arcfox αT5",
        "Arcfox Kaola",
        "Arcfox GT",
        "Arcfox Lite",
        "Arcfox-7",
        "Arcfox ECF",
        "Arcfox α-C"
    ],
    "Acura": [
        "Integra",
        "TLX",
        "RDX",
        "MDX",
        "ZDX",
        "ILX",
        "RLX",
        "CL",
        "TL",
        "TSX",
        "Legend",
        "Vigor",
        "RSX",
        "NSX",
        "SLX",
        "EL",
        "CSX"
    ],
    "Aion": [
        "Aion S",
        "Aion S Plus",
        "Aion V",
        "Aion V Plus",
        "Aion LX",
        "Aion LX Plus",
        "Aion Y",
        "Aion Y Plus",
        "Aion Hyper GT",
        "Aion Hyper SSR",
        "Aion V9",
        "Aion V Pro",
        "Aion LX Pro",
        "Aion Y EV"
    ],
    "AIQAR": [
        "AIQAR Q1",
        "AIQAR Q2",
        "AIQAR X1",
        "AIQAR X3",
        "AIQAR E5",
        "AIQAR E7"
    ],
    "Aito": [
        "Aito M5",
        "Aito M5 Smart Driving Edition",
        "Aito M5 EV",
        "Aito M7",
        "Aito M9",
        "Aito E7"
    ],
    "Alfa Romeo": [
        "Giulia",
        "Stelvio",
        "Tonale",
        "4C",
        "8C Competizione",
        "147",
        "156",
        "159",
        "Brera",
        "GT",
        "GTV6",
        "MiTo",
        "Giulietta",
        "Spider",
        "75",
        "Milano",
        "Alfetta",
        "33",
        "145",
        "146",
        "166",
        "SZ",
        "RZ",
        "Montreal",
        "Giulia Sprint GTA"
    ],
    "AMC": [
        "Gremlin",
        "Hornet",
        "Javelin",
        "AMX",
        "Eagle",
        "Pacer",
        "Matador",
        "Marlin",
        "Rebel",
        "Ambassador",
        "Concord",
        "Spirit",
        "Rambler",
        "M151 MUTT",
        "DJ"
    ],
    "Aston Martin": [
        "DB12",
        "Vantage",
        "DBS",
        "DBX707",
        "Valkyrie",
        "Valhalla",
        "Victor",
        "DB2",
        "DB4",
        "DB5",
        "DB6",
        "DB7",
        "DB9",
        "DB11",
        "V8 Vantage",
        "Lagonda",
        "Vanquish",
        "Virage",
        "One-77",
        "Cygnet",
        "Rapide",
        "Rapide S",
        "DBS Superleggera",
        "Zagato Speedster"
    ],
    "Audi": [
        "A1",
        "A3",
        "A4",
        "A4 Allroad",
        "A5",
        "A6",
        "A6 Allroad",
        "A7",
        "A8",
        "Q2",
        "Q3",
        "Q4 e-tron",
        "Q5",
        "Q7",
        "Q8",
        "Q8 e-tron",
        "TT",
        "R8",
        "e-tron GT",
        "RS e-tron GT",
        "S3",
        "RS3",
        "S4",
        "RS4",
        "S5",
        "RS5",
        "S6",
        "RS6 Avant",
        "S7",
        "RS7",
        "SQ5",
        "SQ7",
        "SQ8",
        "RS Q3",
        "RS Q8",
        "Activesphere",
        "Urbansphere",
        "Skysphere"
    ],
    "Avatr": [
        "Avatr 11",
        "Avatr 12",
        "Avatr E12",
        "Avatr 07"
    ],
    "Avatar": [
        "Avatr 11",
        "Avatr 12",
        "Avatr E12",
        "Avatr 07"
    ],
    "BAIC": [
        "BAIC BJ40",
        "BAIC BJ60",
        "BAIC BJ80",
        "BAIC BJ90",
        "BAIC X55",
        "BAIC X7",
        "BAIC EU5",
        "BAIC EC3",
        "BAIC EX360",
        "BAIC EX3",
        "BAIC Senova D50",
        "BAIC Senova D70",
        "BAIC Senova D80",
        "BAIC Weiwang M50F",
        "BAIC Weiwang 306"
    ],
    "Baojun": [
        "Baojun 310",
        "Baojun 330",
        "Baojun 360",
        "Baojun 510",
        "Baojun 530",
        "Baojun 560",
        "Baojun 730",
        "Baojun RS-3",
        "Baojun RS-5",
        "Baojun E100",
        "Baojun E200",
        "Baojun E300",
        "Baojun E300 Plus",
        "Baojun KiWi EV",
        "Baojun Yunduo"
    ],
    "Baw": [
        "BAW BJ212",
        "BAW BJ2022",
        "BAW BJ80",
        "BAW Yusheng 007",
        "BAW Luba",
        "BAW 306",
        "BAW 307",
        "BAW Qishi EV",
        "BAW Ruixiang"
    ],
    "Bentley": [
        "Continental GT",
        "Continental GTC",
        "Flying Spur",
        "Bentayga",
        "Arnage",
        "Brooklands",
        "Azure",
        "Mulsanne",
        "Turbo R",
        "Eight",
        "T-Series",
        "Continental R",
        "Continental T",
        "EXP 100 GT"
    ],
    "Bertone": [
        "Bertone GB110",
        "Lancia Stratos HF Zero",
        "Alfa Romeo BAT",
        "Lamborghini Miura",
        "Ferrari 250 GT Lusso",
        "Fiat X1/9",
        "Volvo 780",
        "Lamborghini Countach Prototype"
    ],
    "BMW": [
        "1 Series",
        "2 Series",
        "2 Series Gran Coupe",
        "2 Series Active Tourer",
        "3 Series",
        "4 Series",
        "5 Series",
        "6 Series",
        "7 Series",
        "8 Series",
        "M2",
        "M3",
        "M4",
        "M5",
        "M6",
        "M8",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "XM",
        "i3",
        "i4",
        "i5",
        "i7",
        "i8",
        "iX1",
        "iX3",
        "iX",
        "Vision Neue Klasse",
        "Vision M Next",
        "GINA"
    ],
    "Brilliance": [
        "Brilliance BS4",
        "Brilliance BS6",
        "Brilliance H330",
        "Brilliance H530",
        "Brilliance V3",
        "Brilliance V5",
        "Brilliance V7",
        "Brilliance FRV",
        "Brilliance FSV",
        "Brilliance Jinbei"
    ],
    "Bugatti": [
        "Veyron",
        "Chiron",
        "Chiron Super Sport",
        "Chiron Pur Sport",
        "Divo",
        "Centodieci",
        "La Voiture Noire",
        "Bolide",
        "Tourbillon",
        "Type 35",
        "Type 41 Royale",
        "Type 57 Atlantic",
        "EB110"
    ],
    "Buick": [
        "Enclave",
        "Envision",
        "Encore",
        "Encore GX",
        "Envista",
        "LaCrosse",
        "Verano",
        "GL8",
        "Regal",
        "Roadmaster",
        "LeSabre",
        "Skylark",
        "Century",
        "Riviera",
        "Park Avenue",
        "Wildcat"
    ],
    "BYD": [
        "BYD Qin",
        "BYD Qin Plus",
        "BYD Han",
        "BYD Han EV",
        "BYD Tang",
        "BYD Tang DM",
        "BYD Song",
        "BYD Song Plus",
        "BYD Song Pro",
        "BYD Yuan",
        "BYD Yuan Plus",
        "BYD Dolphin",
        "BYD Seal",
        "BYD Seal U",
        "BYD Destroyer 05",
        "BYD Frigate 07",
        "BYD Seagull",
        "BYD e2",
        "BYD e3",
        "BYD e6",
        "Denza D9",
        "Yangwang U8",
        "Yangwang U9",
        "Fang Cheng Bao 5",
        "Fang Cheng Bao 8"
    ],
    "Cadillac": [
        "CT4",
        "CT4-V",
        "CT4-V Blackwing",
        "CT5",
        "CT5-V",
        "CT5-V Blackwing",
        "Escalade",
        "Escalade ESV",
        "Escalade IQ",
        "XT4",
        "XT5",
        "XT6",
        "Lyriq",
        "Celestiq",
        "DeVille",
        "Fleetwood",
        "Eldorado",
        "Seville",
        "STS",
        "DTS",
        "XLR",
        "Allanté",
        "Cimarron",
        "Brougham"
    ],
    "Changan": [
        "Changan CS35",
        "Changan CS55",
        "Changan CS75",
        "Changan CS85",
        "Changan CS95",
        "Changan UNI-K",
        "Changan UNI-T",
        "Changan UNI-V",
        "Changan Eado",
        "Changan Eado Plus",
        "Changan Raeton",
        "Changan Raeton CC",
        "Changan Alsvin",
        "Changan Hunter",
        "Changan Kaicene F70",
        "Changan Kaicene F300",
        "Shenlan SL03",
        "Shenlan S7"
    ],
    "Changfeng": [
        "Liebao Black King Kong",
        "Liebao Heijin",
        "Liebao CS6",
        "Liebao CS7",
        "Qibing",
        "Flying Leopard"
    ],
    "Chery": [
        "Chery Tiggo 2",
        "Chery Tiggo 3",
        "Chery Tiggo 4",
        "Chery Tiggo 5",
        "Chery Tiggo 7",
        "Chery Tiggo 8",
        "Chery Tiggo 9",
        "Chery Arrizo 3",
        "Chery Arrizo 5",
        "Chery Arrizo 6",
        "Chery Arrizo 8",
        "Chery QQ",
        "Chery QQ Ice Cream",
        "Chery Little Ant",
        "Chery eQ1",
        "Chery eQ5",
        "Chery eQ7",
        "Omoda 5",
        "Jaecoo 7",
        "Jaecoo 8"
    ],
    "Chevrolet": [
        "Silverado",
        "Silverado EV",
        "Colorado",
        "Equinox",
        "Equinox EV",
        "Blazer",
        "Blazer EV",
        "Traverse",
        "Tahoe",
        "Suburban",
        "Malibu",
        "Camaro",
        "Corvette",
        "Bolt EV",
        "Bolt EUV",
        "Trailblazer",
        "Trax",
        "Impala",
        "Cruze",
        "Aveo",
        "Sonic",
        "Cobalt",
        "Caprice",
        "Bel Air",
        "Chevelle",
        "El Camino",
        "Monte Carlo",
        "SSR",
        "HHR"
    ],
    "Chrysler": [
        "Chrysler 300",
        "Pacifica",
        "Voyager",
        "Airflow",
        "Sebring",
        "Concorde",
        "PT Cruiser",
        "LHS",
        "Aspen",
        "New Yorker",
        "Imperial",
        "Cirrus",
        "LeBaron"
    ],
    "Citroën": [
        "C3",
        "C3 Aircross",
        "C4",
        "ë-C4",
        "C4 X",
        "C5 Aircross",
        "C5 X",
        "Ami",
        "Berlingo",
        "ë-Berlingo",
        "SpaceTourer",
        "Jumper",
        "2CV",
        "DS",
        "SM",
        "CX",
        "BX",
        "Xantia",
        "Saxo",
        "C6",
        "C8",
        "Visa",
        "GS",
        "GSA"
    ],
    "CPI": [
        "CPI SM 250",
        "CPI SX 250",
        "CPI GTR 50",
        "CPI GTR 125",
        "CPI Oliver City",
        "CPI Aragon GP"
    ],
    "Dacia": [
        "Sandero",
        "Sandero Stepway",
        "Logan",
        "Logan MCV",
        "Duster",
        "Jogger",
        "Spring",
        "Dacia 1300",
        "Nova",
        "Solenza",
        "Lodgy",
        "Dokker",
        "Dacia Pick-Up"
    ],
    "Daewoo": [
        "Daewoo Matiz",
        "Daewoo Lanos",
        "Daewoo Nubira",
        "Daewoo Leganza",
        "Daewoo Espero",
        "Daewoo Tico",
        "Daewoo Cielo",
        "Daewoo Tacuma",
        "Daewoo Korando",
        "Daewoo Musso",
        "Daewoo Kalos"
    ],
    "Daihatsu": [
        "Tanto",
        "Move",
        "Move Canbus",
        "Mira",
        "Mira e:S",
        "Mira Tocot",
        "Cast",
        "Taft",
        "Thor",
        "Rocky",
        "Atrai",
        "Hijet",
        "Gran Max",
        "Sirion",
        "Storia",
        "Terios",
        "Charade",
        "Cuore",
        "Applause",
        "Copen"
    ],
    "Datsun": [
        "Datsun Go",
        "Datsun Go+",
        "Datsun on-DO",
        "Datsun mi-DO",
        "Datsun 240Z",
        "Datsun 260Z",
        "Datsun 280Z",
        "Datsun 510",
        "Datsun 120Y",
        "Datsun 620"
    ],
    "Dayun": [
        "Dayun Yuehu",
        "Dayun Pi1",
        "Dayun Chi",
        "Dayun V9",
        "Dayun E3",
        "Dayun Truck"
    ],
    "DM Telai": [
        "DM Telai Formula Student",
        "DM Telai Prototype"
    ],
    "Dodge": [
        "Challenger",
        "Charger",
        "Durango",
        "Hornet",
        "Viper",
        "Dart",
        "Avenger",
        "Caliber",
        "Journey",
        "Magnum",
        "Neon",
        "Intrepid",
        "Caravan",
        "Grand Caravan"
    ],
    "Dongfeng": [
        "Dongfeng Aeolus Yixuan",
        "Dongfeng Aeolus AX7",
        "Dongfeng Aeolus Haoji",
        "Fengxing T5 EVO",
        "Fengxing Lingzhi",
        "Fengon 580",
        "Fengon ix5",
        "Dongfeng Warrior M50",
        "M-Hero 917",
        "Rich Pickup",
        "Dongfeng E70",
        "Dongfeng EX1"
    ],
    "DS Automobiles": [
        "DS 3",
        "DS 3 Crossback",
        "DS 4",
        "DS 7",
        "DS 7 Crossback",
        "DS 9",
        "DS E-Tense"
    ],
    "Exeed": [
        "Exeed LX",
        "Exeed TXL",
        "Exeed VX",
        "Exeed RX",
        "Exeed Sterra ES",
        "Exeed Sterra ET"
    ],
    "FAW": [
        "Hongqi H5",
        "Hongqi H6",
        "Hongqi H7",
        "Hongqi H9",
        "Hongqi E-HS9",
        "Hongqi L5",
        "Bestune T77",
        "Bestune T99",
        "Bestune B70",
        "Bestune B50",
        "FAW Jiefang",
        "FAW Senia R7",
        "FAW Senia S80"
    ],
    "Ferrari": [
        "296 GTB",
        "296 GTS",
        "SF90 Stradale",
        "SF90 Spider",
        "Roma",
        "Roma Spider",
        "Purosangue",
        "812 GTS",
        "Daytona SP3",
        "Portofino M",
        "F40",
        "F50",
        "Enzo",
        "LaFerrari",
        "458 Italia",
        "488 GTB",
        "Testarossa",
        "360 Modena"
    ],
    "Fiat": [
        "Fiat 500",
        "Fiat 500X",
        "Fiat 500e",
        "Panda",
        "Tipo",
        "Doblo",
        "Fiorino",
        "E-Ulysse",
        "Strada",
        "Pulse",
        "Punto",
        "Bravo",
        "Brava",
        "Uno",
        "Seicento",
        "Cinquecento",
        "Stilo",
        "Linea"
    ],
    "Fisker": [
        "Fisker Ocean",
        "Fisker Pear",
        "Fisker Alaska",
        "Fisker Karma",
        "Karma Revero"
    ],
    "Ford": [
        "Mustang",
        "Mustang Mach-E",
        "F-150",
        "F-150 Lightning",
        "Ranger",
        "Bronco",
        "Bronco Sport",
        "Escape",
        "Kuga",
        "Edge",
        "Explorer",
        "Expedition",
        "Maverick",
        "Transit",
        "Transit Connect",
        "Focus",
        "Fusion",
        "Mondeo",
        "Fiesta",
        "Taurus",
        "Crown Victoria",
        "GT",
        "GT40",
        "Probe"
    ],
    "Foton": [
        "Foton Tunland",
        "Foton Aumark",
        "Foton Auman",
        "Foton View",
        "Foton Gratour",
        "Foton MP-X",
        "Foton Sauvana",
        "Foton iBlue"
    ],
    "GAC": [
        "Trumpchi GS3",
        "Trumpchi GS4",
        "Trumpchi GS5",
        "Trumpchi GS8",
        "GAC Empow",
        "GAC GA4",
        "GAC GA6",
        "Aion S",
        "Aion LX",
        "Aion Y",
        "Aion V",
        "Hyper SSR"
    ],
    "Geely": [
        "Geely Coolray",
        "Geely Binyue",
        "Geely Tugella",
        "Geely Emgrand",
        "Geely Emgrand L",
        "Geely Emgrand EV",
        "Geely Geometry A",
        "Geely Geometry C",
        "Geely Geometry E",
        "Geely Xingyue L",
        "Geely Panda Mini",
        "Geely Boyue",
        "Geely Okavango"
    ],
    "Genesis": [
        "Genesis G70",
        "Genesis G80",
        "Genesis G90",
        "Genesis GV60",
        "Genesis GV70",
        "Electrified GV70",
        "Genesis GV80",
        "Electrified GV80",
        "Genesis Essentia"
    ],
    "GMC": [
        "Sierra",
        "Sierra EV",
        "Canyon",
        "Terrain",
        "Acadia",
        "Yukon",
        "Yukon XL",
        "Hummer EV Pickup",
        "Hummer EV SUV",
        "Savana"
    ],
    "Great Wall": [
        "Haval H6",
        "Haval Jolion",
        "Haval Big Dog",
        "Wey Coffee 01",
        "Wey Mocha",
        "Ora Good Cat",
        "Ora Ballet Cat",
        "Ora Lightning Cat",
        "Tank 300",
        "Tank 500",
        "Poer Pickup"
    ],
    "Haval": [
        "Haval Jolion",
        "Haval H2",
        "Haval H6",
        "Haval H9",
        "Haval Dargo",
        "Haval Big Dog",
        "Haval F7",
        "Haval F7x",
        "Haval M6",
        "Haval Cool Dog"
    ],
    "Honda": [
        "Civic",
        "Civic Type R",
        "Accord",
        "CR-V",
        "HR-V",
        "ZR-V",
        "CR-Z",
        "Fit",
        "Jazz",
        "City",
        "Insight",
        "Pilot",
        "Passport",
        "Ridgeline",
        "Honda e",
        "Freed",
        "Odyssey",
        "Prelude",
        "S2000",
        "Element",
        "Crosstour",
        "NSX"
    ],
    "Hongqi": [
        "Hongqi H5",
        "Hongqi H7",
        "Hongqi H9",
        "Hongqi E-HS9",
        "Hongqi E-HS3",
        "Hongqi S9",
        "Hongqi L5",
        "Hongqi H6",
        "Hongqi HS7"
    ],
    "Huawei": [
        "Huawei Inside M5",
        "Huawei Inside M7",
        "Huawei Inside M9",
        "Huawei Concept"
    ],
    "Hummer": [
        "Hummer EV Pickup",
        "Hummer EV SUV",
        "Hummer H1",
        "Hummer H2",
        "Hummer H3"
    ],
    "Hyundai": [
        "Elantra",
        "Avante",
        "Sonata",
        "Accent",
        "Verna",
        "Tucson",
        "Santa Fe",
        "Palisade",
        "Kona",
        "Kona Electric",
        "Ioniq",
        "Ioniq 5",
        "Ioniq 6",
        "Nexo",
        "Venue",
        "Staria",
        "Casper",
        "Tiburon",
        "Coupe",
        "Azera",
        "Veloster",
        "Genesis Coupe"
    ],
    "IM Motors": [
        "IM L7",
        "IM LS7",
        "IM LS6",
        "IM V7"
    ],
    "Infiniti": [
        "Q50",
        "Q60",
        "QX50",
        "QX55",
        "QX60",
        "QX80",
        "Q70",
        "Q70L",
        "QX30",
        "QX4"
    ],
    "Iran Khodro": [
        "Samand",
        "Dena",
        "Runna",
        "Soren",
        "Tara",
        "Peugeot 405",
        "Peugeot Pars",
        "Peugeot 206",
        "Peugeot 207"
    ],
    "Isuzu": [
        "D-Max",
        "MU-X",
        "Trooper",
        "Rodeo",
        "Isuzu Elf",
        "Isuzu Giga"
    ],
    "Iveco": [
        "Iveco Daily",
        "Iveco Eurocargo",
        "Iveco Stralis",
        "Iveco S-Way",
        "Iveco PowerStar"
    ],
    "Izh": [
        "Izh 2125",
        "Izh 2126",
        "Izh Oda",
        "Izh 21251",
        "Izh Jupiter"
    ],
    "JAC": [
        "JAC S2",
        "JAC S3",
        "JAC S4",
        "JAC S5",
        "JAC S7",
        "JAC iEV6E",
        "JAC iEV7S",
        "JAC iEV7L",
        "JAC T8",
        "JAC Refine M4",
        "JAC Heyue",
        "JAC JS4"
    ],
    "Jaguar": [
        "XE",
        "XF",
        "XJ",
        "F-Pace",
        "E-Pace",
        "I-Pace",
        "F-Type",
        "XJ220",
        "S-Type",
        "X-Type",
        "XK",
        "Mark II",
        "Daimler Double Six"
    ],
    "Jeep": [
        "Wrangler",
        "Wrangler 4xe",
        "Grand Cherokee",
        "Grand Cherokee L",
        "Compass",
        "Renegade",
        "Cherokee",
        "Gladiator",
        "Wagoneer",
        "Grand Wagoneer",
        "Liberty",
        "Commander",
        "Patriot"
    ],
    "Jetour": [
        "Jetour X70",
        "Jetour X70S",
        "Jetour X90",
        "Jetour X95",
        "Jetour X90 Plus",
        "Jetour Shanhai L9",
        "Jetour X50"
    ],
    "Karsan": [
        "Karsan Jest",
        "Karsan Atak",
        "Karsan Star",
        "Karsan V-1",
        "Karsan e-ATAK"
    ],
    "Kia": [
        "Picanto",
        "Morning",
        "Rio",
        "K3",
        "Forte",
        "K5",
        "Optima",
        "Stinger",
        "Seltos",
        "Sportage",
        "Sorento",
        "Telluride",
        "Carnival",
        "Sedona",
        "EV6",
        "EV9",
        "Soul",
        "Cadenza",
        "Opirus",
        "Ceed"
    ],
    "Lamborghini": [
        "Revuelto",
        "Aventador",
        "Huracán",
        "Urus",
        "Sián",
        "Countach LPI 800-4",
        "Essenza SCV12",
        "Gallardo",
        "Murciélago",
        "Diablo",
        "Miura",
        "Jalpa",
        "Espada",
        "LM002"
    ],
    "Lancia": [
        "Ypsilon",
        "Delta",
        "Thema",
        "Stratos",
        "Fulvia",
        "Beta",
        "Montecarlo",
        "Kappa",
        "Thesis"
    ],
    "Land Rover": [
        "Defender",
        "Discovery",
        "Discovery Sport",
        "Range Rover",
        "Range Rover Sport",
        "Range Rover Velar",
        "Range Rover Evoque",
        "Freelander",
        "LR2",
        "LR3",
        "LR4"
    ]
}

CAR_MAKES_MODELS.update(CAR_MODELS_UPDATE)

ADDITIONAL_MAKES = {
    "Arcfox": [],
    "Acura": [],
    "Aion": [],
    "AIQAR": [],
    "Aito": [],
    "Alfa Romeo": [],
    "AMC": [],
    "Aston Martin": [],
    "Audi": [],
    "Avatar": [],
    "Avatr": [],
    "Baic": [],
    "Baojun": [],
    "Baw": [],
    "Bentley": [],
    "Bertone": [],
    "BMW": [],
    "Brilliance": [],
    "Bugatti": [],
    "Buick": [],
    "BYD": [],
    "Cadillac": [],
    "Changan": [],
    "Changfeng": [],
    "Chery": [],
    "Chevrolet": [],
    "Chrysler": [],
    "Citroen": [],
    "CPI": [],
    "Dacia": [],
    "Daewoo": [],
    "Daihatsu": [],
    "Datsun": [],
    "Dayun": [],
    "DM Telai": [],
    "Dodge": [],
    "Dongfeng": [],
    "DS Automobiles": [],
    "Exeed": [],
    "FAW": [],
    "Ferrari": [],
    "Fiat": [],
    "Fisker": [],
    "Ford": [],
    "Forthing": [],
    "Foton": [],
    "GAC": [],
    "GAZ": [],
    "Geely": [],
    "Genesis": [],
    "GMC": [],
    "Gonow": [],
    "Great wall": [],
    "Hafei": [],
    "Haval": [],
    "Hiphi": [],
    "Honda": [],
    "Hongqi": [],
    "Huawei": [],
    "Huawei Inside": [],
    "Hummer": [],
    "Hyster": [],
    "Hyundai": [],
    "IM Motors": [],
    "Infiniti": [],
    "Iran Khodro": [],
    "Isuzu": [],
    "Iveco": [],
    "Izh": [],
    "JAC": [],
    "Jaguar": [],
    "Jeep": [],
    "Jetour": [],
    "Karsan": [],
    "Kia": [],
    "Lamborghini": [],
    "Lancia": [],
    "Land Rover": [],
    "Leapmotor": [],
    "Lexus": [],
    "Lifan": [],
    "Lincoln": [],
    "Linde": [],
    "Lixiang": [],
    "Lonking": [],
    "Lotus": [],
    "LTI": [],
    "Lucid": [],
    "Lynk & Co": [],
    "Mahindra": [],
    "Maserati": [],
    "Maxus": [],
    "Maybach": [],
    "Mazda": [],
    "Mclaren": [],
    "Mercedes-Benz": [],
    "Mercury": [],
    "MG": [],
    "Mini": [],
    "Mitsubishi": [],
    "Mitsuoka": [],
    "Moskvich": [],
    "MPM": [],
    "Neta": [],
    "Niewiadow": [],
    "NIO": [],
    "Nissan": [],
    "Oldsmobile": [],
    "OMODA": [],
    "Opel": [],
    "Peugeot": [],
    "Polestar": [],
    "Pontiac": [],
    "Porsche": [],
    "Proton": [],
    "Renault": [],
    "Renault Samsung": [],
    "Rivian": [],
    "Roewe": [],
    "Rolls-Royce": [],
    "Rover": [],
    "Saab": [],
    "Saleen": [],
    "Saturn": [],
    "Scion": [],
    "Seat": [],
    "Sena": [],
    "Skoda": [],
    "Skywell": [],
    "Smart": [],
    "Soueast": [],
    "Ssangyong": [],
    "Subaru": [],
    "Sunbeam": [],
    "Suzuki": [],
    "Tank": [],
    "Tata": [],
    "Tesla": [],
    "Toyota": [],
    "UAZ": [],
    "Vauxhall": [],
    "VAZ": [],
    "Volkswagen": [],
    "Volvo": [],
    "Voyah": [],
    "Wey": [],
    "Wuling": [],
    "Xiaomi": [],
    "Xingtai": [],
    "Xpeng": [],
    "YTO": [],
    "Yuanxin Energy's": [],
    "ZAZ": [],
    "Zeekr": [],
    "Zukida": [],
    "Zxauto": [],
}

for make, models in ADDITIONAL_MAKES.items():
    CAR_MAKES_MODELS.setdefault(make, models)

ENGINE_LITERS = ["1.0L", "1.2L", "1.4L", "1.5L", "1.6L", "1.8L", "2.0L", "2.2L", "2.4L", "2.5L", "3.0L", "3.5L", "3.6L", "4.0L", "4.6L", "5.0L", "5.7L", "6.0L", "6.2L", "Electric"]

ENGINE_CYLINDERS = ["3 cylinders", "4 cylinders", "5 cylinders", "6 cylinders", "8 cylinders", "10 cylinders", "12 cylinders", "16 cylinders", "Electric Motor", "Hybrid", "Rotary"]

YEARS = list(range(2025, 1979, -1))  # 2025 down to 1980

CATEGORIES = ["Sedan", "SUV", "Coupe", "Hatchback", "Convertible", "Wagon", "Pickup Truck", "Van", "Sports Car", "Luxury"]

GEARBOX_OPTIONS = ["Manual", "Automatic", "Semi-Automatic", "CVT", "DSG"]

STEERING_OPTIONS = ["Left-hand drive", "Right-hand drive"]

DRIVE_OPTIONS = ["Front-wheel drive (FWD)", "Rear-wheel drive (RWD)", "All-wheel drive (AWD)", "Four-wheel drive (4WD)"]

DOORS_OPTIONS = ["2/3", "4/5", "5+"]

COLORS = [
    "White", "Black", "Silver", "Gray", "Red", "Blue", "Green", "Yellow",
    "Orange", "Brown", "Beige", "Gold", "Purple", "Pink", "Burgundy",
    "Navy", "Teal", "Charcoal", "Pearl White", "Metallic Gray", "Matte Black",
    "Matte Gray", "Turquoise", "Lime Green", "Bronze", "Copper", "Champagne",
    "Graphite", "Ivory", "Magenta"
]

INTERIOR_MATERIALS = ["Cloth", "Leather", "Synthetic Leather", "Alcantara", "Suede", "Vinyl"]

INTERIOR_COLORS = [
    "Black", "Gray", "Beige", "Tan", "Brown", "White", "Red", "Blue",
    "Cream", "Ivory", "Two-tone", "Chocolate"
]

FUEL_TYPES = ["Gasoline", "Diesel", "Electric", "Hybrid", "Plug-in Hybrid", "Hydrogen", "CNG", "LPG"]
