"""Add engine and other car details

Revision ID: b5756d140581
Revises: 
Create Date: 2025-10-05 16:26:43.140652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5756d140581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_liters', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('engine_cylinders', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=32), nullable=True))
        batch_op.drop_column('engine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('engine_cylinders')
        batch_op.drop_column('engine_liters')

    # ### end Alembic commands ###
